# Generated by Django 5.0.3 on 2024-04-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='description',
            new_name='Received_From',
        ),
    ]
