# Generated by Django 5.0.3 on 2024-04-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_rename_description_userincome_received_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='Received_From',
            new_name='description',
        ),
    ]
